/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ACKNOWLEDGE, acknowledge_t, AUTO)


PB_BIND(PRESSURE_READING, pressure_reading_t, AUTO)


PB_BIND(IMU_READING, imu_reading_t, AUTO)


PB_BIND(TELEMETRY_PACKET, telemetry_packet_t, AUTO)


PB_BIND(GNSS_POSITION, gnss_position_t, AUTO)


PB_BIND(GNSS_STATUS, gnss_status_t, AUTO)


PB_BIND(SET_SUDO, set_sudo_t, AUTO)


PB_BIND(CLEAR_FLASH, clear_flash_t, AUTO)


PB_BIND(READ_FLASH, read_flash_t, AUTO)


PB_BIND(FLASH_DATA, flash_data_t, AUTO)


PB_BIND(READY_UP, ready_up_t, AUTO)


PB_BIND(ENTER_IDLE, enter_idle_t, AUTO)


PB_BIND(TRIGGER_PYRO, trigger_pyro_t, AUTO)


PB_BIND(FJALAR_DATA, fjalar_data_t, AUTO)


PB_BIND(FJALAR_MESSAGE, fjalar_message_t, AUTO)




